// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ApsantaScanner._2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "ApsantaScanner.VS2022.859beb0f-db5a-4861-917b-00c25df38ec3";
        public const string Name = "ApsantaScanner.VS2022";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Dmitry Balikhin";
        public const string Tags = "";
    }
}
