// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VisualStudio2022
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisualStudio2022.e65637ff-6efa-4c3f-8f40-c1463750cd0a";
        public const string Name = "VisualStudio2022";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Dmitry Balikhin";
        public const string Tags = "";
    }
}
